# Generated by Django 5.2.4 on 2025-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
