# Generated by Django 5.2.4 on 2025-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('partial_ready', 'Partially Ready'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
