# Generated by Django 5.2.4 on 2025-08-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_hls_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_updated_at',
        ),
    ]
