# Generated by Django 5.2.3 on 2025-07-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
    ]
